{
  "formatVersion": "1.1",
  "component": {
    "group": "cryptocreeklib",
    "module": "cryptocreeklib",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cryptocreeklib-1.0.1.jar",
          "url": "cryptocreeklib-1.0.1.jar",
          "size": 2108,
          "sha512": "5d8a9b54fc9934110b457d97477cd279d33e2bb22d9339d144039ccdf2519766bb251a6178e84d53edf493ccff2ee7b9747dad8a07d5c19961c299e9d4b60902",
          "sha256": "3098bd10c03c7d6f0ce6b3525f6ed966507ed1d2586d26443f8097013b0b0413",
          "sha1": "44020a01045c20c330b4bfd73ab6c7e7e741130e",
          "md5": "0cc4de4aba418342b71b348dc0537df8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.2.2"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.2.2"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.2.2"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.2.2"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "cryptocreeklib-1.0.1.jar",
          "url": "cryptocreeklib-1.0.1.jar",
          "size": 2108,
          "sha512": "5d8a9b54fc9934110b457d97477cd279d33e2bb22d9339d144039ccdf2519766bb251a6178e84d53edf493ccff2ee7b9747dad8a07d5c19961c299e9d4b60902",
          "sha256": "3098bd10c03c7d6f0ce6b3525f6ed966507ed1d2586d26443f8097013b0b0413",
          "sha1": "44020a01045c20c330b4bfd73ab6c7e7e741130e",
          "md5": "0cc4de4aba418342b71b348dc0537df8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cryptocreeklib-1.0.1-javadoc.jar",
          "url": "cryptocreeklib-1.0.1-javadoc.jar",
          "size": 80513,
          "sha512": "7ad074d6e0845b5f3fd715d952ae2a1660337eb21ac8b224320139c3d358aeda4e0dbe03399fe29de0c3f9aeb011ea8b882a07d0039125fd3b64d980d9c70047",
          "sha256": "07ebd898dae01f17f63f64d36ca6d201380b0891fd0da7dde6acf8f872b7af50",
          "sha1": "8adf4d8a11a56955b4760dcb65ddfe79f6fd7eb4",
          "md5": "51cba53c00b23d1398c29bf00b31af80"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cryptocreeklib-1.0.1-sources.jar",
          "url": "cryptocreeklib-1.0.1-sources.jar",
          "size": 1540,
          "sha512": "1bc28c4656b826a9619c7cb025ad13148a85194eb8ce0571e7bf45fd89dcd3343bc4aad10eb5814eff48bb14e32cf5bd3a50fe29384b20a351bf927ca21e6b04",
          "sha256": "516fad5aaf659d334f64be9a8b3a17fe8bee903abae02709d0b423c667500529",
          "sha1": "c5ff869fb4a9821368da5e1391550b5aed7a912e",
          "md5": "edffb3a2cc9f1963e8c5ce8e6164edf5"
        }
      ]
    }
  ]
}
