{
  "formatVersion": "1.1",
  "component": {
    "group": "cryptocreeklib",
    "module": "cryptocreeklib",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cryptocreeklib-1.0.0.jar",
          "url": "cryptocreeklib-1.0.0.jar",
          "size": 2079,
          "sha512": "f4bfabc81bbd7331ce6cf26e61ff0cc725d04679614fc842cc5efb71b52ba3b5f66a062ff3588dc929939c152e9a414f12f07ec3352e3ad0c4bc116e81a18649",
          "sha256": "4cc40f82d82541f6f9dfd982336d5c7801dfbf5cdde15a1fe9127a7b3170d1a4",
          "sha1": "b4e0f6345e5b3302c5f6f852625d2d8305524b85",
          "md5": "f4b75b1a2b533216104f5703bc312d0f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.2.2"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.2.2"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.2.2"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.2.2"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "cryptocreeklib-1.0.0.jar",
          "url": "cryptocreeklib-1.0.0.jar",
          "size": 2079,
          "sha512": "f4bfabc81bbd7331ce6cf26e61ff0cc725d04679614fc842cc5efb71b52ba3b5f66a062ff3588dc929939c152e9a414f12f07ec3352e3ad0c4bc116e81a18649",
          "sha256": "4cc40f82d82541f6f9dfd982336d5c7801dfbf5cdde15a1fe9127a7b3170d1a4",
          "sha1": "b4e0f6345e5b3302c5f6f852625d2d8305524b85",
          "md5": "f4b75b1a2b533216104f5703bc312d0f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cryptocreeklib-1.0.0-javadoc.jar",
          "url": "cryptocreeklib-1.0.0-javadoc.jar",
          "size": 79609,
          "sha512": "8cb8132bd0f145c86943761895a14ac57256732217733be73644ee946a6a5e52ef025f96db1240d85c6d69276aa067f646bdce6a0e96c7a83b2b1d0e0908a519",
          "sha256": "fe75014de330fb5aec509431202014d20116acbd284aa2099e3609cf58772181",
          "sha1": "cded80115997925455f0ccf9d80f609e0593d9cd",
          "md5": "1cbddbaa2e5d00035d87e2f252d037ad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cryptocreeklib-1.0.0-sources.jar",
          "url": "cryptocreeklib-1.0.0-sources.jar",
          "size": 984,
          "sha512": "aea47b373b9df3864854031afd0aaaf38993e779b8b22079774a32ffebb03b162d651a7ddca384896d4e88f24ef19d6f25cb6d9c756b5394664d59f1a6ae00b2",
          "sha256": "84ba4f55fc9b5c7058c100307ef73ea1d94da963069546a1bcdf06108f72d683",
          "sha1": "09415f918dfaa697406fab295e93401601023d71",
          "md5": "6b1f78a64000e99fa06aaefbfaec0029"
        }
      ]
    }
  ]
}
