{
  "formatVersion": "1.1",
  "component": {
    "group": "cryptocreeklib",
    "module": "cryptocreeklib",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cryptocreeklib-1.0.0.jar",
          "url": "cryptocreeklib-1.0.0.jar",
          "size": 2108,
          "sha512": "a003bb5dd6af88f0963117ea3ec04e94f006752f27690cdc9ebee0d5fa2e5e9df18d4c39de82e41b5d794b5adbe9242979e85ba5a0c4ec06ffc24c41054c3d10",
          "sha256": "8ddeabeba3b098c1f040682dde63f5c6bc0892ff4c097baad509e106a0da0209",
          "sha1": "5aea5a1af267825951a385ec6831867d8f4bbeef",
          "md5": "db2158ca5aa504678e02aa295ab93a3e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.2.2"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.2.2"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.2.2"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.2.2"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "cryptocreeklib-1.0.0.jar",
          "url": "cryptocreeklib-1.0.0.jar",
          "size": 2108,
          "sha512": "a003bb5dd6af88f0963117ea3ec04e94f006752f27690cdc9ebee0d5fa2e5e9df18d4c39de82e41b5d794b5adbe9242979e85ba5a0c4ec06ffc24c41054c3d10",
          "sha256": "8ddeabeba3b098c1f040682dde63f5c6bc0892ff4c097baad509e106a0da0209",
          "sha1": "5aea5a1af267825951a385ec6831867d8f4bbeef",
          "md5": "db2158ca5aa504678e02aa295ab93a3e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cryptocreeklib-1.0.0-javadoc.jar",
          "url": "cryptocreeklib-1.0.0-javadoc.jar",
          "size": 80518,
          "sha512": "cb80410f1edb9babbd7848dd742896f16bff6aa79aa043d2d53cb8e4a389b760d2520d4b50574d5b89192f68ca742c2cd598d043470cf250483bb83997a01315",
          "sha256": "2e12572b2fb7e05db7f1976a489bf19f630df68bcb35fb9e70c4d9268e4c2484",
          "sha1": "c4fb1092e16b2cc8cb570f3b1b0abff5392e9c58",
          "md5": "f523bfce7c24185b93bcc0a97f964e9c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cryptocreeklib-1.0.0-sources.jar",
          "url": "cryptocreeklib-1.0.0-sources.jar",
          "size": 1540,
          "sha512": "32315969ea1c0e365613edfa27ef36d2e36e7827549cfface5fbcdc788d0d05fc4cdb337159c284c1dbcaf38eaec630ef111526b86bd43da2cc8e274912b3318",
          "sha256": "8089d5a81246f02bf18ec3a2231e1173dda3f01cb67004196f8cd437e755a438",
          "sha1": "610e3d2031356a82f07645cba6621eb5f4e6af6f",
          "md5": "c9a589b139971d380a0651df46eadb5b"
        }
      ]
    }
  ]
}
