{
  "formatVersion": "1.1",
  "component": {
    "group": "cryptocreeklib",
    "module": "cryptocreeklib",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cryptocreeklib-1.0.0.jar",
          "url": "cryptocreeklib-1.0.0.jar",
          "size": 2108,
          "sha512": "1bd4125417dcebbe7f4c82ff682e10632048ff540453ea891e0d749f92ffa140fc13ac00ac0d53da2ab63daf4a790c56b289604a7acdec60ae7b70f689610ef3",
          "sha256": "642751ae11ebc20e24f34d6fe8162b4dd6cb9727434125b144b5fb958b90060a",
          "sha1": "aca6ff8e62082d6458a7431afcc26497c903ec17",
          "md5": "13bb9643e578a3f0962adb4409a6c4e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.2.2"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.2.2"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.2.2"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.2.2"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "cryptocreeklib-1.0.0.jar",
          "url": "cryptocreeklib-1.0.0.jar",
          "size": 2108,
          "sha512": "1bd4125417dcebbe7f4c82ff682e10632048ff540453ea891e0d749f92ffa140fc13ac00ac0d53da2ab63daf4a790c56b289604a7acdec60ae7b70f689610ef3",
          "sha256": "642751ae11ebc20e24f34d6fe8162b4dd6cb9727434125b144b5fb958b90060a",
          "sha1": "aca6ff8e62082d6458a7431afcc26497c903ec17",
          "md5": "13bb9643e578a3f0962adb4409a6c4e4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cryptocreeklib-1.0.0-javadoc.jar",
          "url": "cryptocreeklib-1.0.0-javadoc.jar",
          "size": 80518,
          "sha512": "af3f7e45ec2d4850c93f77b4282525ef6cb677effd486dfcc4680b3f0b538928840980f60d1b84fac612f80472c7a696bd839346d07eb82c2513c77a96c8b6b1",
          "sha256": "3a93b915b6abf3ff6e1f88e8132960be8c343d7fa77983f2bc78bf475727bd29",
          "sha1": "64ef99377e0ee234f5fce4f0e3851697934b05ea",
          "md5": "fb51c44e1eaa55b50e0e20cd2b7e7a74"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cryptocreeklib-1.0.0-sources.jar",
          "url": "cryptocreeklib-1.0.0-sources.jar",
          "size": 1540,
          "sha512": "cfb8812c8c2c579b7a72135fe3221b83b2dc50c03ddcf6195905e925d1e6d99e5971da2deb2c2f373846e29e9c6770cc221008029cc5e5e8a5bfb67818faaa60",
          "sha256": "32d3b0490bc4c1e7dc065dc428cf9c626d45779e7786fa8fd45beb829a02a1a2",
          "sha1": "e4c7b56469d38a954e76315b587038d4dee2cf0c",
          "md5": "09dfc6d95a861fa2bd2f6d18b2453f41"
        }
      ]
    }
  ]
}
